version: '3.7'
services:  

  rabbitmq-service:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-service
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
    environment:
      TZ: "America/Lima"
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  cassandra-service:
    image: bitnami/cassandra:3.11.13
    container_name: cassandra-service
    ports:
      - "9042:9042"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    volumes:
      - cassandra-vol:/bitnami
    environment:
      TZ: "America/Lima"
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "12345678"
      CASSANDRA_PASSWORD_SEEDER: "yes"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4096M

  zipkin-service:
    image: openzipkin/zipkin:2.24.4
    container_name: zipkin-service
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    environment:
      TZ: "America/Lima"
      ## RABBIT, for development or testing RABBIT_CONCURRENCY: 2, for production RABBIT_CONCURRENCY: 4 or above
      RABBIT_ADDRESSES: rabbitmq-service:5672
      RABBIT_QUEUE: 'zipkin'
      RABBIT_USER: 'guest'
      RABBIT_PASSWORD: 'guest'
      RABBIT_VIRTUAL_HOST: '/'
      RABBIT_CONCURRENCY: 2
      ## CASSANDRA, for development or testing CASSANDRA_MAX_CONNECTIONS: 4, for production CASSANDRA_MAX_CONNECTIONS: 8 or above
      STORAGE_TYPE: cassandra3
      CASSANDRA_CONTACT_POINTS: cassandra-service:9042
      CASSANDRA_ENSURE_SCHEMA: 'true'
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "12345678"
      CASSANDRA_MAX_CONNECTIONS: 4
    ## for development or testing DEBUG, for production INFO
    command: --logging.level.zipkin2=DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M

networks:
  salesforce-spring-network:
    external: true

volumes:
  rabbitmq-vol:
  cassandra-vol:
