version: '3.7'
services:  

  rabbitmq-service:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-service-new
    ports:
      - "19672:15672"
      - "5972:5672"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    volumes:
      - rabbitmq_vol_new:/var/lib/rabbitmq
    environment:
      TZ: "America/Lima"
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: '12345678'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

## https://hub.docker.com/_/cassandra
  # cassandra-service:
  #   image: cassandra:3.11.12
  #   container_name: cassandra-service-new
  #   ports:
  #     - "9942:9042"
  #   restart: unless-stopped
  #   networks:
  #     - salesforce-spring-network
  #   volumes:
  #     - cassandra_vol_new:/var/lib/cassandra
  #   environment:
  #     TZ: "America/Lima"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "20"
  #   deploy:
  #     resources:
  #       limits:
  #         # for development or testing: 4 cpu min server host, for production: 8 cpu min server host
  #         cpus: '0.50'
  #         # for development or testing min value: 4096M (4G), for production min value: 6144M (6G), recomended value: 8192M (8G)
  #         memory: 4096M

## https://hub.docker.com/r/bitnami/cassandra
## openzipkin/zipkin no funciona con version de cassandra 4 (ultima testeada bitnami/cassandra:4.1.3), solo con version 3
  cassandra-service:
    image: bitnami/cassandra:3.11.13
    container_name: cassandra-service-new
    ports:
      - "9942:9042"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    volumes:
      - cassandra_vol_new:/bitnami
    environment:
      TZ: "America/Lima"
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "12345678"
      CASSANDRA_PASSWORD_SEEDER: "yes"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          # for development or testing: 4 cpu min server host, for production: 8 cpu min server host
          cpus: '0.50'
          # for development or testing min value: 4096M (4G), for production min value: 6144M (6G), recomended value: 8192M (8G)
          memory: 4096M

  zipkin-service:
    image: openzipkin/zipkin:2.24.4
    container_name: zipkin-service-new
    ports:
      - "9911:9411"
    restart: unless-stopped
    networks:
      - salesforce-spring-network
    environment:
      TZ: "America/Lima"
      ## RABBIT, for development or testing RABBIT_CONCURRENCY: 2, for production RABBIT_CONCURRENCY: 4 or above
      RABBIT_ADDRESSES: rabbitmq-service-new:5672
      RABBIT_QUEUE: 'zipkin'
      RABBIT_USER: 'guest'
      RABBIT_PASSWORD: '12345678'
      RABBIT_VIRTUAL_HOST: '/'
      RABBIT_CONCURRENCY: 2      
      ## CASSANDRA, for development or testing CASSANDRA_MAX_CONNECTIONS: 4, for production CASSANDRA_MAX_CONNECTIONS: 8 or above
      STORAGE_TYPE: cassandra3
      CASSANDRA_CONTACT_POINTS: cassandra-service-new:9042
      CASSANDRA_ENSURE_SCHEMA: 'true'
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "12345678"
      CASSANDRA_MAX_CONNECTIONS: 4
    ## for development or testing DEBUG, for production INFO
    command: --logging.level.zipkin2=DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "20"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M

networks:
  salesforce-spring-network:
    external: true

volumes:
  rabbitmq_vol_new:
  cassandra_vol_new:
